apiVersion: v1
kind: Pod 
metadata:
   name: three-containers
   labels:
     purpose: demonstrate-multi-container
spec:
  containers:
    - name: nginx-container-1
      image: bitnami/nginx
      env:
       - name: NGINX_HTTP_PORT_NUMBER
         value: "8080"
      ports:
       - containerPort: 8080
    - name: nginx-container-2
      image: bitnami/nginx
      env:
        - name: NGINX_HTTP_PORT_NUMBER
          value: "8081"
      ports:
       - containerPort: 8081
    
    - name: nginx-container-3
      image: bitnami/nginx
      env:
        - name: NGINX_HTTP_PORT_NUMBER
          value: "8082"
      ports:
       - containerPort: 8082
    