apiVersion: v1
kind: Pod
metadata: 
   name: port-forwarding-multiple
   labels:
    purpose: testing
spec:
 containers:
   - name: nginx-container-testing-multiple-0
     image: bitnami/nginx
     env:
       - name: NGINX_HTTP_PORT_NUMBER
         value: "8080"
     ports:
       - containerPort: 8080
   - name: nginx-container-testing-multiple-1
     image: bitnami/nginx
     env:
       - name: NGINX_HTTP_PORT_NUMBER
         value: "8081"
     ports:
       - containerPort: 8081